### ISSUE TITLE
Adding tab at index strange behavior

### ISSUE THREAD

**Issue by blindmanonacid** [jmuxfeldt/TabbedView2#2]
Hi,

when specifying an index to add a new tab it adds itself at the right place but clicking around on the tabs in the GUI afterwards gives some strange behavior. Clicking tabs before and including the inserted index selects it as normal but clicking a tab at an index after the inserted tab selects the tab at an index-1. Dragging any tab and releasing it or adding a new tab without specifying an index seems to set it back to normal behavior.

This is only an issue with TabbedView2, not TabbedView. Tested on MacOS and Windows with QT.

To reproduce:
```
(
w= Window("tabs", Rect(0, 0, 600, 300)).front;
t= TabbedView2(w, Rect(20, 50, 550, 300));
t.add("tab1");
t.add("tab2");
t.add("tab3");
t.add("tab4");
t.add("tab5");
t.add("tab6");
t.add("tab7");
t.add("tab8");
t.add("tab9");
t.add("tabInsert", 4); // add "tabInsert" at index 4
)
```

Also, thanks a lot for this quark, I use it a lot :)

**Comment by jmuxfeldt** [comment]
Thanks for the bug report. It may be a while before I have time to debug this, but I will.

**Comment by jmuxfeldt** [comment]
"Dragging any tab and releasing it or adding a new tab without specifying an index seems to set it back to normal behavior." This reindexes the tabs, so my guess is, I need to call a reindexing function after a tab is inserted.

**Comment by jmuxfeldt** [comment]
for a quickfix, you can do:
`(
w= Window("tabs", Rect(0, 0, 600, 300)).front;
t= TabbedView2(w, Rect(20, 50, 550, 300));
t.add("tab1");
t.add("tab2");
t.add("tab3");
t.add("tab4");
t.add("tab5");
t.add("tab6");
t.add("tab7");
t.add("tab8");
t.add("tab9");
t.add("tabInsert", 4); // add "tabInsert" at index 4
t.tabViews.do{|t,i| t.pr_setIndex(i);}

)
`

**Comment by jmuxfeldt** [comment]
OK, I pushed the fix. Please let me know if it causes any side-effects. I am simply re-indexing on refresh.

**Comment by blindmanonacid** [comment]
Great, thank you. After testing with my code I see no side-effects on my side.
